workflows:
  build-android:
    name: Build Debug APK
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get

      - name: Build APK (with verbose output)
        script: |
          flutter build apk --debug -v

      - name: Locate APK files (debug step)
        script: |
          echo "Searching for APK files..."
          find . -name "*.apk"

    artifacts:
      - '**/app-debug.apk'
      - '**/*.apk'
