workflows:
  build-android:
    name: Build Debug APK
    environment:
      flutter: stable
      java: 17
      vars:
        JAVA_TOOL_OPTIONS: "-Xmx8192m"
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --debug
    artifacts:
      - build/app/**/*.apk
