workflows:
  build-android:
    name: Build Debug APK
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
      - build/app/outputs/apk/debug/app-debug.apk
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/apk/release/app-release.apk
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/apk/debug/*.apk
      - build/app/outputs/apk/release/*.apk

