workflows:
  build-android:
    name: Build Debug APK
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Build Debug APK
        script: |
          flutter build apk --debug -v
    artifacts:
      - build/**/outputs/**/*.apk

  build-ios:
    name: Build iOS (No Codesign)
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Build iOS without codesigning
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
      - build/ios/**/*.app
